version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server




  mysql_server:
    image: mysql:8.0
    environment:
     - MYSQL_DATABASE=coffe_pos
     - MYSQL_USER=root 
     - MYSQL_PASSWORD=admin 
     - MYSQL_ROOT_PASSWORD=admin 